version: '3.4'

services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER}
        QUARTO_VERSION: ${QUARTO_VERSION}
    user: ${USER}
    volumes:
      - ..:/workspace:cached
      - ${RENV_PATHS_CACHE_HOST}:/renv/cache
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
    env_file: .env
    
  db:
    image: mongo:3.4
    command: mongod --port 12335
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: testdb
    ports:
      - 12335:27017
      
  quizpostgresdb:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postdb-data:/data/db

  rstudiodevcontainer:
    build:
      context: ./rstudio_docker
      args:
        S6_VERSION: ${S6_VERSION}
        RSTUDIO_VERSION: ${RSTUDIO_VERSION}
        QUARTO_VERSION: ${QUARTO_VERSION}
    volumes:
      - ${VOLUME_PATH}:${VOLUME_PATH}
      - /home/${USER}/.ssh:/home/${USER}/.ssh
      - ${RENV_PATHS_CACHE_HOST}:${RENV_PATHS_CACHE_CONTAINER}
      - ${VOLUME_PATH}/.devcontainer/rstudio_config_dir:/home/${USER}/.config/rstudio
    restart:
      unless-stopped
    ports:
      - ${LOCAL_PORT}:8787
    env_file: .env
    
volumes:
  mongodb-data:
  postdb-data:
